{
 "title": "lab07 dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "hello_requests_total" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "prometheus_target_scrape_pool_sync_total"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request duration on helloworld",
   "type": "timeseries",
   "description": "Monitors the duration based on histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(hello_request_duration_seconds_bucket{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request type distribution",
   "type": "bargauge",
   "description": "Plot based on counter vec",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_per_type{instance=~\"$instance\"}",
     "legendFormat": "{{method}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Request rate helloworld - rate 5m",
   "type": "timeseries",
   "description": "Monitors the request rate based on counter",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(hello_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service uptime",
   "type": "stat",
   "description": "Plot based on gauge incremented by ticker",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime_measure{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Monitors the status code for prometheus job executions",
   "type": "timeseries",
   "description": "This job looks if a prometheus scraping ended successfully (200) had an error (500) and so on.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=~\"$job\"}[5m])",
     "legendFormat": "{{job}} - {{code}}"
    }
   ]
  }
 ]
}