version: '3'
services:
  redis:
    image: redis:3.2.10
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - db:/data
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=upb
      - POSTGRES_PASSWORD=upb
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local